### ISSUE TITLE
example is broken

### ISSUE THREAD

**Issue by gerchicov-bp** [karthikAdaptavant/AppBottomActionSheet#1]
examle directory contains podfile. Ok run `pod install`:

```[!] Unable to find a target named `AppBottomActionSheet_Tests`, did find `AppBottomActionSheet_Example`.```

**Comment by vladvlasov256** [comment]
Did you run .xcproject or .xcworkspace?

**Comment by dilipiOSDeveloper** [comment]
can i customize that display UI ?

**Comment by karthiikmk** [comment]
yes you can customize.
